name: Crypto Actions Signer
description: An action that executes a query, signs the result and sends it back to the origin.
inputs:
  github-token:
    desciption: A GitHub personal access token to make API calls and post issues to other oracle repositories.
    required: true
  rpc-node:
    description: An ethereum RPC node.
    required: true
  wallet-key:
    description: The key for the Ethereum account to sign data.
    required: true
  contract-address:
    description: The address of the signer contract.
    required: true
runs:
  using: node12
  main: dist/index.js
