name: GitHub Data Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Oracle Request
    runs-on: ubuntu-latest
    steps:
      uses: cryptoactions/signer@593fa08f4aaf9a4b206d3d7876cd6f8746093a4b
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        rpc-node: ${{ secrets.RPC_NODE }}
        wallet-key: ${{ secrets.WALLET_KEY }}
        contract-address: 0xd022f3294f34gd022f32d022f3294f34cd012f32