name: GitHub Data Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Oracle Request
    runs-on: ubuntu-latest
    steps:
      - uses: cryptoactions/signer@main
        with:
          github-token: ${{ secrets.PAT }}
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract-address: "0xf1C55Eef5486b8F1c8B66d3c326A14E1De7EA627"