name: GitHub Data Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Oracle Request
    runs-on: ubuntu-latest
    steps:
      - uses: cryptoactions/signer@main
        with:
          github-token: ${{ secrets.PAT }}
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}
          contract-address: "0x64bfe49E4e4De18F9512bF12BA00ffAE4756B955"