name: GitHub Workflow Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Workflow Run
    runs-on: ubuntu-latest
    steps:
      - uses: cryptoactions/signer@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}