name: GitHub Workflow Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Workflow Run
    runs-on: ubuntu-latest
    steps:
      - uses: cryptoactions/signer@f3b2600665da805e4a7e30f220641758280a7b1e
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          rpc-node: ${{ secrets.RPC_NODE }}
          wallet-key: ${{ secrets.WALLET_KEY }}