name: GitHub Workflow Signer
on:
  issues:
    types: [ opened ]

jobs:
  sign:
    name: Sign Workflow Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4
        with:
          script: |
            const request = JSON.parse(context.payload.issue.body)
            const workflowRunUrl = `https://api.github.com/repos/${request.owner}/${request.repo}/actions/runs/${request.run}`
            const workflowRun = await github.request(workflowRunUrl)
            const workflow = await github.request(workflowRun.data.workflow_url)
            const workflowFile = await github.request('GET /repos/{owner}/{repo}/contents/{path}', {
              owner: request.owner,
              repo: request.repo,
              path: workflow.data.path,
              ref: workflowRun.data.head_sha
            })
            console.log(workflowFile.data.sha)